"""migration_2

Revision ID: 3b89d02cbeea
Revises: f9efdb54193e
Create Date: 2022-11-16 10:50:54.195094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b89d02cbeea'
down_revision = 'f9efdb54193e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('listings', sa.SmallInteger(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('on_kijiji_from', sa.String(), nullable=True),
    sa.Column('avg_reply', sa.String(), nullable=True),
    sa.Column('reply_rate', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.SmallInteger(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_ad_id'), 'items', ['ad_id'], unique=False)
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('overview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('hydro', sa.Boolean(), nullable=True),
    sa.Column('heat', sa.Boolean(), nullable=True),
    sa.Column('water', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.SmallInteger(), nullable=True),
    sa.Column('agreement_years', sa.SmallInteger(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overview_id'), 'overview', ['id'], unique=False)
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.SmallInteger(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('laundry', sa.Boolean(), nullable=True),
    sa.Column('dishwasher', sa.Boolean(), nullable=True),
    sa.Column('fridge', sa.Boolean(), nullable=True),
    sa.Column('air_conditioning', sa.Boolean(), nullable=True),
    sa.Column('outdoor_spase', sa.String(), nullable=True),
    sa.Column('smoking_permitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_overview_id'), table_name='overview')
    op.drop_table('overview')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_index(op.f('ix_items_ad_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
