"""migration_1

Revision ID: a7a6c892526e
Revises: a2b4a632768e
Create Date: 2022-11-17 21:35:59.636955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a6c892526e'
down_revision = 'a2b4a632768e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
