"""migration_11

Revision ID: f74a8b1bb5c2
Revises: 98de8dc0bfc7
Create Date: 2022-11-18 22:58:02.003047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74a8b1bb5c2'
down_revision = '98de8dc0bfc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
